project_name: resolume-timecode
before:
  hooks:
    - go mod download
builds:
#  - id: darwin-amd64
#    main: ./
#    binary: golang-cross
#    goos:
#      - darwin
#    goarch:
#      - amd64
#    env:
##      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
##      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
#      - CC=o64-clang
#      - CXX=o64-clang++
#    flags:
#      - -mod=readonly
#      - -trimpath
#    ldflags:
#      - -s -w
#      - -X main.version={{.Version}}
#    mod_timestamp: '{{ .CommitTimestamp }}'
#    hooks:
#      post: upx {{ .Path }}
#  - id: darwin-m1
#    main: ./
#    binary: golang-cross
#    goos:
#      - darwin
#    goarch:
#      - arm64
#    env:
##      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
##      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
#      - CC=oa64-clang
#      - CXX=oa64-clang++
#    flags:
#      - -mod=readonly
#      - -trimpath
#    ldflags:
#      - -s -w
#      - -X main.version={{.Version}}
#    mod_timestamp: '{{ .CommitTimestamp }}'
#    hooks:
#      post: upx {{ .Path }}
  - goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -H=windowsgui
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post: upx {{ .Path }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs?:'
      - '^tests?:'
release:
  github:
    owner: chabad360
    name: resolume-timecode
  draft: true
  prerelease: auto
archives:
  - format_overrides:
      - goos: windows
        format: zip
#    replacements:
#      darwin: mac