project_name: resolume-timecode
before:
  hooks:
    - go install github.com/tc-hib/go-winres@latest
    - go install fyne.io/fyne/v2/cmd/fyne
    - go mod download
    - go-winres make --product-version=git-tag --file-version=git-tag
builds:
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -mod=readonly
      - -trimpath
    tags:
      - gles
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post: 
      - upx {{ .Path }}
      - fyne package --os darwin --exe dist/darwin_darwin_amd64/resolume-timecode --icon images/logo.png --id "me.chabad360.resolume-timecode"   
#   - id: windows-amd64  
#     goos:
#       - windows
#     goarch:
#       - amd64
#     env:
#       - CGO_ENABLED=1
#       - CC=x86_64-w64-mingw32-gcc
#       - CXX=x86_64-w64-mingw32-g++
#     flags:
#       - -mod=readonly
#       - -trimpath
#     ldflags:
#       - -s -w
#       - -X main.version={{.Version}}
#       - -H=windowsgui
#     mod_timestamp: '{{ .CommitTimestamp }}'
#     hooks:
#       post: upx {{ .Path }}
checksum:
  name_template: 'checksums.txt'
universal_binaries:
  - id: darwin
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs?:'
      - '^tests?:'
release:
  github:
    owner: chabad360
    name: resolume-timecode
  draft: true
  prerelease: auto
archives:
  - format: zip
    wrap_in_directory: true
    replacements:
      darwin: macOS
