project_name: resolume-timecode
before:
  hooks:
    - go get github.com/tc-hib/go-winres@latest
    - go mod download
    - go-winres make --product-version=git-tag --file-version=git-tag
builds:
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.Date={{.CommitDate}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - upx {{ .Path }}
        - sh macos.sh resolume-timecode images/logo.svg "me.chabad360.resolume-timecode" {{ .Major }} {{ .Minor }}
        - cp {{ .Path }} resolume-timecode.app/Contents/MacOS/
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.Date={{.CommitDate}}
      - -H=windowsgui
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post: upx {{ .Path }}
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^ci:'
      - '^docs?:'
      - '^tests?:'
release:
  github:
    owner: chabad360
    name: resolume-timecode
  draft: true
  prerelease: auto
archives:
  - id: darwin
    builds:
      - darwin
    format: zip
    wrap_in_directory: true
    replacements:
      darwin: macOS
    files:
      - LICENSE
      - README.MD
      - resolume-timecode.app
  - id: windows
    builds:
      - windows
    format: zip
    wrap_in_directory: true