name: Release

on:
  push:

jobs:
  goreleaser:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3
      
      - name: Install Packages
        run: brew install mingw-w64 upx
          
      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/go
            ~/.cache/go-build
            ~/Library/Caches/go-build
          #  %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --debug release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#       - name: VirusTotal Scan
#         uses: crazy-max/ghaction-virustotal@v2
#         with:
#           vt_api_key: ${{ secrets.VT_API_KEY }}
#           files: dist/resolume-timecode_windows_amd64/resolume-timecode.exe

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          path: dist
